Создает главную страницу
htmlacademy-htmlcss/1992251-sedona-33 pull request #2
Opened 2022-01-25 11:27 UTC by Nabolina

2022-01-26 05:17 UTC, redsmoke19 requested changes
Наташа привет! Ты большая молодец и отлично справилась с первой ДЗ. У меня есть несколько замечаний, которые ты можешь прочитать ниже, но в целом все очень и очень хорошо! И еще момент, ты должна правильно форматировать свой код, что бы все теги были на своих местах и что бы была видна вложенноть элементов. Это можно легко сделать - если ты работатешь на Win и в  VSCode то просто воспользуйся комбинацией клавиш Alt + Shift + F. 

Если будут вопросы по замечаниям - обязательно пиши и все обсудим)

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +    <!--p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p-->
Этот комментарий можно удалить

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +  <a class="navigation-logo" href="index.html">
Тут все правильно, молодец, что сделала ссылку в которой логотип, но смотри, мы находимся на главной странице сейчас и плохой практикой является давайть ссылку на страницу, на которой мы находимся - т.е. на саму себя. Поэтому тут все оставляй как есть, только просто удали полностью атрибут href="index.html"

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +<a class="navidation-link" href="index.html">Главная</a>
Тут на же история с ссылой что и на лого

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +<li class="navidation-item">
Смотри, во первый у тебя опечатка в названии классов - `navidation` а должно `navigation`. И еще момент, у тебя это два разный списка, первый список это список ссылок, а второй это уже пользовательская навигация, а классы для элементов списка у тебя одинаковые, так не пойдет - это внесен сложности в дальнейшем при стилизации

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +<a class="navidation-link" href="#">Хочу сюда</a>
И вот эта ссылка - она видишь отичается от остальных элементов того же списка, поэтому лучше эту ссылку сделать отдельной от списка

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +          <header class="header-promo">
Тут тег `header` лишний, его можно заменить на простой div

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +            <h2 class="header-title">Седона&nbsp;&mdash; небольшой городок в&nbsp;Аризоне, заслуживающий большего!</h2>
Тут хотел похвалить - молодец что воспользовалась мнемоникой )

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +              </ul>
Молодец что сделала вложенный список)

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +          <ul class="advantages-list">
Вот тут только для других элементов нужно тоже делать их как элементы все того же первого списка, Они видишь у тебя даже пронумерованы, это значит что все преимущества должны быть одним списков, и внутри одного большого списка могут быть еще и вложенные списки)

Т.е. у тебя есть пять нумерованных преимущества - это список один. Далее внутри первого преимущества есть еще один вложенный список, которые ты уже реализовала остлось в этот первый список добавить остальные преимущества

```html
<ul>
    <li> // первое преимущество
        <ul>
            <li>
                // первое вложенное преимущество первого преимущества 
            </li>
        </ul>
    </li>
    <li></li> // второе преимущество
    <li></li> // третье преимущество
    <li></li> // четвертое
    <li></li> // пятое
</ul>
```

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +            <p class="search-date">Укажите предполагаемые даты поездки,<br> и&nbsp;мы&nbsp;покажем вам лучшие предложения гостиниц в&nbsp;Седоне
тег br использовать не желательно, нужно от него избавиться

2022-01-26 05:17 UTC, redsmoke19 commented on index.html
> +              <li class="footer-social-item"> <a class="button footer-social-link" href="https://twitter.com/htmlacademy_ru"><span class="visually-hidden">Twitter</span></a> </li>
тут в этих ссылках не нужно миксовать второй класс `button` потому что потом мы будет стилизовать и все ссылки в которых у тебя будет класс `button` будут иметь одинаковый вид

2022-01-26 15:05 UTC, Nabolina commented on index.html
> +  <a class="navigation-logo" href="index.html">
Спасибо. Все понятно

2022-01-26 15:05 UTC, Nabolina commented on index.html
> +<a class="navidation-link" href="index.html">Главная</a>
Понятно. Исправляю

2022-01-26 20:44 UTC, Nabolina commented on index.html
> +<li class="navidation-item">
Ой, исправила

2022-01-26 20:45 UTC, Nabolina commented on index.html
> +            <h2 class="header-title">Седона&nbsp;&mdash; небольшой городок в&nbsp;Аризоне, заслуживающий большего!</h2>
Ура!

2022-01-26 20:45 UTC, Nabolina commented on index.html
> +          <ul class="advantages-list">
Изменила

2022-01-26 20:45 UTC, Nabolina commented on index.html
> +              <li class="footer-social-item"> <a class="button footer-social-link" href="https://twitter.com/htmlacademy_ru"><span class="visually-hidden">Twitter</span></a> </li>
Ок

2022-01-26 20:45 UTC, Nabolina commented on index.html
> +            <p class="search-date">Укажите предполагаемые даты поездки,<br> и&nbsp;мы&nbsp;покажем вам лучшие предложения гостиниц в&nbsp;Седоне
ок

2022-01-27 05:30 UTC, redsmoke19 requested changes
Наташа привет! Ты молодец - все замечания мастерски тобой были исправлены на главной странице! Так же отдельно хотел заметить, что ты молодец что пишешь ответные комментарии в коде, это круто) По главной страницы осталвся один вопрос, и по странце каталога тоже посмотри замечания - их нужно исправить)

2022-01-27 05:30 UTC, redsmoke19 commented on index.html
> +      <header class="header-promo">
Не исправлено!

2022-01-27 05:30 UTC, redsmoke19 commented on index.html
> +          <div class="advantages-image"> <img alt="Настоящий городок" src=""> </div>
Вот тут div обертка будет лишней

2022-01-27 05:30 UTC, redsmoke19 commented on index.html
> +          <div class="advantages-image"> <img alt="Мост Дьявола" src=""> </div>
80 строчка - div обертка лишняя

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +    <header class="inner-header">
Наташа, вот тут тег header будет лишним, все его содержимое нужно перенести в секцию, ту что у тебя пониже, это считается один большой блок с заголовком, breadcrumbs и формой, вот так:

```html
<section>
    <h1></h1>
    <ul></ul>
    <form action=""></form>
</section>
```

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +                <input class="control-input" type="radio" name="housing" value="hotel">
Вся форма у тебя отлично сделана, только вот смотри, у тебя чекбоксы и радио кнопки имеют одинаковый класс, но стилизоваться они будут по разному, поэтому тут для радио кнопок тебе нужно придумать другой класс)

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +      <span class="catalog-hotels-found">Найдено гостиниц: 38</span>
А вот от сюда у тебя должна начинаться уже следующая секция, в которой будет:
```html
<section>
    <h2></h2> - Зголовок "Найдено гостиниц"
    <select></select>
    <ul></ul> - Это список кнопок отображения http://joxi.ru/J2bokZDUq5XOvA - а это именно должен быть список
    <ul></ul> - а это уже список карточек гостиниц
</section>
```

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +              <button class="hotel-card-button hotel-card-button-blue" type="submit">В избранное</button>
type="submit" для всех таких кнопок Избранное нужно удалить - ведь при нажатии мы ни чего не должны отправлять )

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +              <b class="hotel-card-star">&#9733; &#9733; &#9733; &#9733;</b>
Тега b нужно заменить на span или p

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +          <button class="button pagination-show-more" type="button">Загрузить ещё</button>
А вот тут лучше сделать не кнопку, а ссылку - по макету подразумевается что при нажатии на нее мы будем переходить на другую страницу где будет большой список гостиниц

2022-01-27 05:30 UTC, redsmoke19 commented on catalog.html
> +          <span class="pagination-number">Гостиниц на странице:</span>
Тут семантичесики лучше использовать p

2022-01-27 10:58 UTC, Nabolina commented on index.html
> +          <header class="header-promo">
+

2022-01-27 10:59 UTC, Nabolina commented on index.html
> +      <header class="header-promo">
Ой, пропустила  в ночи

2022-01-27 14:22 UTC, Nabolina commented on index.html
> +          <div class="advantages-image"> <img alt="Настоящий городок" src=""> </div>
ок

2022-01-27 14:22 UTC, Nabolina commented on index.html
> +          <div class="advantages-image"> <img alt="Мост Дьявола" src=""> </div>
ок

2022-01-27 14:24 UTC, Nabolina commented on catalog.html
> +    <header class="inner-header">
ок

2022-01-27 14:32 UTC, Nabolina commented on catalog.html
> +                <input class="control-input" type="radio" name="housing" value="hotel">
Надеюсь, правильно поняла

2022-01-27 14:36 UTC, Nabolina commented on catalog.html
> +      <span class="catalog-hotels-found">Найдено гостиниц: 38</span>
ок

2022-01-27 14:37 UTC, Nabolina commented on catalog.html
> +              <button class="hotel-card-button hotel-card-button-blue" type="submit">В избранное</button>
ок

2022-01-27 14:38 UTC, Nabolina commented on catalog.html
> +              <b class="hotel-card-star">&#9733; &#9733; &#9733; &#9733;</b>
ок

2022-01-27 14:40 UTC, Nabolina commented on catalog.html
> +          <button class="button pagination-show-more" type="button">Загрузить ещё</button>
Понятно. Я думала, что на этой странице будут подгружаться гостиницы, то есть все будет происходить на той же странице

2022-01-28 04:57 UTC, merged